name = "i-potato-you"  # 项目名，和Cloudflare上的Worker名一致
main = "src/index.js"  # 代码入口文件
compatibility_date = "2026-01-08"  # 兼容性日期（用当前日期即可）
name = "i-potato-you"
main = "src/index.js"
compatibility_date = "2026-01-09"

kv_namespaces = [
  { binding = "MOVIE_TABLE", id = "38feee4365a24226b6c1779988cdde67" }
]
